#!/bin/bash

if ( whoami != root); then
	echo "This script needs to run as root to function properly"
	exit 1
fi

npm install --python=python2.7.1
errorcode=$?
if [ $errorcode != 0 ]; then
    echo "npm install exited with error code $errorcode"
	echo "make sure you have python 2.7.1 installed"
    exit $errorcode
fi

npm install -g grunt-cli --python=python2.7.1
errorcode=$?
if [ $errorcode != 0 ]; then
    echo "npm install -g grunt-cli exited with error code $errorcode"
    exit $errorcode
fi

npm install -g bower --python=python2.7.1
errorcode=$?
if [ $errorcode != 0 ]; then
    echo "npm install -g bower exited with error code $errorcode"
    exit $errorcode
fi

(cd client && bower install);
errorcode=$?
if [ $errorcode != 0 ]; then
    echo "bower install exited with error code $errorcode"
    exit $errorcode
fi

exit 0;